apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
type: Opaque
stringData:
  pg_host: jdbc:postgresql://surus.db.elephantsql.com:5432/hzrsgpxr 
  pg_user: hzrsgpxr
  pg_password: AyXvZ3ZoeDF1W3s8qLG7uwTUKFtDBQTa
  consul_host: http://10.244.1.32:8500
  cloudinary_cloud_name: dwon7bysc
  cloudinary_api_key: "283841692368561"
  cloudinary_api_secret: RpZtPsloGfauKDeeqoSkEjkBRmk