
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: booking-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /v1/listings
            backend:
              serviceName: listings-service
              servicePort: 8080
          - path: /v1/reservations
            backend:
              serviceName: reservations-service
              servicePort: 8080
          - path: /v1/images
            backend:
              serviceName: images-service
              servicePort: 8080
          - path: /
            backend:
              serviceName: frontend-r
              servicePort: 80